### ISSUE TITLE
can not add repository 

### ISSUE THREAD

**Issue by amangautam1** [kyonifer/koma#34] opened 2017-07-19 21:36 UTC
On adding the repository in the Gradle I am getting the following error.

Java: file not found Exception
Resource nexus-maven-repository-index-properties does not exist

![img_20170720_031330](https://user-images.githubusercontent.com/25130654/28391465-cdf4ecae-6cfb-11e7-8c82-f80fcb5663b5.jpg)

**Comment by kyonifer** [comment] 2017-07-19 23:57
Hi,

How are you adding koma to your project? For a gradle project, you'll want to add koma into the repositories block of your `build.gradle` file.

For example, here's a `build.gradle` for a Java project thats configured to use koma:

```groovy
apply plugin: "java"
apply plugin: "application"

mainClassName="Hello"

repositories { 
    maven { 
        url "http://dl.bintray.com/kyonifer/maven" 
        jcenter()
    } 
}
dependencies{
    compile "koma:backend-matrix-mtj:0.10"
    compile "koma:core:0.10"
}
```
then making `src/main/java/Hello.java` contain:
```java
class Hello {
    public static void main(String [] args) {
        System.out.println(koma.Koma.zeros(3,3));
    }
}
```
We can now run it on the command line:
```
❯ gradle run
:compileJava UP-TO-DATE
:processResources NO-SOURCE
:classes UP-TO-DATE
:run
mat[ 0.00,  0.00,  0.00 end
     0.00,  0.00,  0.00 end
     0.00,  0.00,  0.00 ]
```
Or import it into intellij as a gradle project. If you're running things from intellij make sure you refresh the gradle project after changing the build.gradle file.

If you're using maven instead of gradle you can find the xml snippet [here](https://bintray.com/kyonifer/maven/core) to add.

**Comment by amangautam1** [comment] 2017-07-20 07:43
this is my gradle file and i am still getting same error.

```
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.1.3-2'

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'kotlin'
apply plugin: 'application'

mainClassName = "_DefaultPackage"

repositories {
    maven {
        url "http://dl.bintray.com/kyonifer/maven"
        jcenter()
    }
}
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:$kotlin_version"
    compile "com.marcinmoskala:DiscreteMathToolkit:1.0.2"
    compile 'com.github.kevinsawicki:http-request:6.0'
    compile "koma:backend-matrix-mtj:0.10"
    compile "koma:core:0.10"

}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

**Comment by kyonifer** [comment] 2017-07-20 13:13
I can't reproduce. With your `build.gradle` I get:
```bash
❯ gradle build
:compileKotlin
Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre8/1.1.3-2/kotlin-stdlib-jre8-1.1.3-2.pom
Download https://jcenter.bintray.com/com/github/kevinsawicki/http-request/6.0/http-request-6.0.pom
Download https://jcenter.bintray.com/com/marcinmoskala/DiscreteMathToolkit/1.0.2/DiscreteMathToolkit-1.0.2.pom
Download http://dl.bintray.com/kyonifer/maven/koma/backend-matrix-mtj/0.10/backend-matrix-mtj-0.10.pom
Download http://dl.bintray.com/kyonifer/maven/koma/core/0.10/core-0.10.pom
Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.1.3-2/kotlin-stdlib-jre7-1.1.3-2.pom
Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre8/1.1.3-2/kotlin-stdlib-jre8-1.1.3-2.jar
Download https://jcenter.bintray.com/com/github/kevinsawicki/http-request/6.0/http-request-6.0.jar
Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.1.3-2/kotlin-stdlib-jre7-1.1.3-2.jar
Download https://jcenter.bintray.com/com/marcinmoskala/DiscreteMathToolkit/1.0.2/DiscreteMathToolkit-1.0.2.jar
:compileJava
:copyMainKotlinClasses
:processResources NO-SOURCE
:classes
:jar
:startScripts
:distTar
:distZip
:assemble
:compileTestKotlin NO-SOURCE
:compileTestJava NO-SOURCE
:copyTestKotlinClasses
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL in 6s
8 actionable tasks: 8 executed
```

What does `gradle build` give you?

**Comment by kyonifer** [comment] 2017-07-20 14:44
Doing a search for your error leads to [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/208379885-Maven-repo-indexing-problems-), which notes there's an open issue for [user bintray repositories not indexing correctly in intellij](https://youtrack.jetbrains.com/issue/IDEA-138029). This appears to be the exact issue you're running into.

Following the steps noted in that bug report (pressing `'Update' in File | Settings | Build, Execution, Deployment | Build Tools | Maven | Repositories for the created repository`) I'm able to reproduce your error. Reimporting the project eliminates it until I try to update the repository index again. 

Closing this as I'm fairly confident this isn't anything to do with koma and is the above bug in intellij's indexer.

**Closed by kyonifer** 2017-07-20 14:44 UTC
